### ISSUE TITLE
Real value of pi

### ISSUE THREAD

**Issue by bytccoin** [pi-apps/LatinChain#12]
How can I know the real value of Pi in the market or traditional exchanges? Or how can the value be defined when exchanging it for a physical item? There are online exchanges that They put a speculative price on what it would be worth if it were on the exchanges, but how do they speculate that value? And will it reach that level?

**Comment by rockcesar** [comment]
@bytccoin Everything after OpenMainnet. Everything is speculative before OpenMainnet.
