### ISSUE TITLE
Télécom 

### ISSUE THREAD

**Issue by 58120599** [pi-apps/LatinChain#14]
![IMG-20241108-WA0033](https://github.com/user-attachments/assets/a33767de-e7c5-4e76-96c0-b248e085d4ab)
![IMG-20241103-WA0004](https://github.com/user-attachments/assets/037b9b38-f602-4059-83ad-d771a6b10684)
![Uploading IMG-20241106-WA0067.jpg…]()

**Comment by rockcesar** [comment]
Cool!.
